### ISSUE TITLE
City Name in transform.py

### ISSUE THREAD

**Issue by triandicAnt** [akshaykc/BICapstoneTeam23#2]
I think we are creating the optimal number of topics based on the following city:
    df2 = df1[df1.city == "Scottsdale"] line 32
We have to generate on "Pittsburg" data.
Please confirm.

**Comment by akshaykc** [comment]
no no
 in hte file it says scottsdale

But I have saved the graph of pittsburgh when I ran it before
scottsdale and based on that I decided number of topics

**Comment by triandicAnt** [comment]
okay !
